#!/bin/bash

# Hostname list
DNSHOST=p5-dns.5700.network
HTTPHOSTS=(p5-http-a.5700.network p5-http-b.5700.network p5-http-c.5700.network p5-http-d.5700.network p5-http-e.5700.network p5-http-f.5700.network p5-http-g.5700.network)

# HTTP and DNS server directory names
DNSDIR='dns_server'
HTTPDIR='http_server'

# Extract the argument parameters
while getopts p:o:n:u:i: args
do
	case $args in
		p)
			port=$OPTARG
			;;
		o)
			origin=$OPTARG
			;;
		n)
			name=$OPTARG
			;;
		u)
			username=$OPTARG
			;;
		i)
			keyfile=$OPTARG
			;;
		?)
			echo "usage: ./deployCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>"
			exit 1
			;;
	esac
done

# Deploy the CDN servers
printf "Deploying CDN servers...\n\n"
for host in "${HTTPHOSTS[@]}"
do
	printf "[Deploying CDN Server at $username@$host]...\n"
	# Remove existing file directory and create a new one
	ssh -i $keyfile $username@$host "rm -rf ~/$HTTPDIR; mkdir ~/$HTTPDIR/"
	# Download the pageviews.csv file
	ssh -i $keyfile $username@$host "cd $HTTPDIR; wget https://www.dropbox.com/s/tfo6h9jwfvkvcpt/pageviews.csv"
	# Copy over the HTTP server files
	scp -i $keyfile httpserver httpcacher utils.py $username@$host:~/$HTTPDIR/
	# Run the HTTP Cacher script to cache the results during the deployment phase
	ssh -i $keyfile $username@$host "cd $HTTPDIR; ./httpcacher -o $origin"
	printf "DEPLOYED: CDN Server at $username@$host...\n\n"
done

# Deploy the DNS server
printf "Deploying DNS server...\n"
# Remove existing file directory and create a new one
ssh -i $keyfile $username@$DNSHOST "rm -rf ~/$DNSDIR; mkdir ~/$DNSDIR/"
# Copy over the DNS server files
scp -i $keyfile dnsserver utils.py $username@$DNSHOST:~/$DNSDIR/
# Download the GeoIP database
ssh -i $keyfile $username@$DNSHOST "cd $DNSDIR; wget https://www.dropbox.com/s/jj91bijakzzb9sr/geoip.tag.gz; tar -xvzf geoip.tag.gz; rm -f geoip.tag.gz"
# Download the GeoIP Vendor
ssh -i $keyfile $username@$DNSHOST "cd $DNSDIR; wget https://www.dropbox.com/s/lf9bymoxg5qjoii/vendor.tag.gz; tar -xvzf vendor.tag.gz; rm -f vendor.tag.gz"
printf "DEPLOYED: DNS Server at $username@$DNSHOST...\n\n"
