#!/bin/bash

# Hostname list
DNSHOST=p5-dns.5700.network
HTTPHOSTS=(p5-http-a.5700.network p5-http-b.5700.network p5-http-c.5700.network p5-http-d.5700.network p5-http-e.5700.network p5-http-f.5700.network p5-http-g.5700.network)

# HTTP and DNS server directory names
DNSDIR='dns_server'
HTTPDIR='http_server'

# Extract the argument parameters
while getopts p:o:n:u:i: args
do
	case $args in
		p)
			port=$OPTARG
			;;
		o)
			origin=$OPTARG
			;;
		n)
			name=$OPTARG
			;;
		u)
			username=$OPTARG
			;;
		i)
			keyfile=$OPTARG
			;;
		?)
			echo "usage: ./stopCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>"
			exit 1
			;;
	esac
done

# Stop the CDN servers
printf "Stopping CDN servers...\n\n"
for host in "${HTTPHOSTS[@]}"
do
	printf "[Stopping CDN server at $username@$host]...\n"
	# Stop all running python processes in the servers
	ssh -i $keyfile $username@$host "killall -u $username httpserver"
	ssh -i $keyfile $username@$host "killall -u $username python3"
	# Remove the HTTP file directory from the server (clean up)
	ssh -i $keyfile $username@$host "rm -rf ~/$HTTPDIR"
	printf "STOPPED: CDN server at $username@$host...\n\n"
done

printf "Stopping DNS server at $username@$DNSHOST...\n"
# Stop all running python processes in the servers
ssh -i $keyfile $username@$DNSHOST "killall -u $username dnsserver"
ssh -i $keyfile $username@$DNSHOST "killall -u $username python3"
# Remove the DNS file directory from the server (clean up)
ssh -i $keyfile $username@$DNSHOST "rm -rf ~/$DNSDIR"
printf "STOPPED: DNS server at $username@$DNSHOST...\n\n"
